### ISSUE TITLE
Messages get stuck after a `MessageDecodeError`

### ISSUE THREAD

**Issue by Levyks** [minghuaw/fe2o3-amqp#232]
I've noticed that, when implementing something like the example below:

```rs
#[derive(Debug, Deserialize)]
#[serde(tag = "t", content = "c")]
pub enum MyMessage {
    Foo(String),
}
// FromBody and FromEmptyBody impl

let received = receiver.recv::<MyMessage>().await;
```

If I send something like this in that receiver's queue
```json
{ "t": "Bar", "c": "Hello World!" }
```

I get a `MessageDecodeError`, which makes sense, however, the message is not rejected after it, and the error itself does not provide the `DeliveryInfo` necessary for me to do it myself, making the message be stuck as `delivering` in the queue until the connection is dropped.

Would it be possible to implement an `auto-reject` option to deal with this case? Or maybe just include the `DeliveryInfo` inside the error?

I haven't checked all the variants of the `RecvError` enum, but maybe there's a chance of that happening in other cases as well?

**Comment by Levyks** [comment]
As a workaround, I thought about just receiving a generic `Body<Value>` and dealing with the deserialization myself, but I couldn't figure out how to turn that into a `MyMessage` enum after that, since apparently `serde_amp` only implements a `from_reader` and a `from_slice`

**Comment by minghuaw** [comment]
> #[serde(tag = "t", content = "c")]

Most of these serde tags are targeted at JSON and a lot of them don't make sense for other encoding (including AMQP). There's a high chance that the decoding error is caused by these tags.

> Would it be possible to implement an auto-reject option to deal with this case? Or maybe just include the DeliveryInfo inside the error?

Good idea. I prefer the latter option but it would require a breaking release. A better way might be allowing user to set a handler function/closure that has access to the receiver and delivery info. I'll give this a try. 

> but I couldn't figure out how to turn that into a MyMessage enum after that

`serde_amqp` has this method `from_value` https://docs.rs/serde_amqp/latest/serde_amqp/fn.from_value.html

**Comment by minghuaw** [comment]
The message decode error now carries the delivery info in 0.10.0 https://docs.rs/fe2o3-amqp/0.10.0/fe2o3_amqp/link/enum.RecvError.html#variant.MessageDecode

**Comment by minghuaw** [comment]
@Levyks Would you consider this issue resolved?

**Comment by Levyks** [comment]
yeah, sorry for not closing it
