### ISSUE TITLE
AMQP version negotiation not working if initiated by broker

### ISSUE THREAD

**Issue by weigangd** [minghuaw/fe2o3-amqp#33]
The last bullet point in chapter **2.2 Version Negotiation** in the specification says the following:
`Note that if the server only supports a single protocol version, it is consistent with the above rules for the server to send its protocol header prior to receiving anything from the client and to subsequently close the socket if the client’s protocol header does not match the server’s.`
This is currently not working because in the SASL authorization can read too many bytes from the TcpStream. I'll link a workaround PR which fixed the issue for me but I think it could be handled more elegantly.

**Comment by minghuaw** [comment]
Thank you for raising the issue. I felt like the problem could be that the `Transport` might be mistakenly reading too many bytes. I will investigate that

**Comment by minghuaw** [comment]
I think the problem is caused by my improper use of `self.framed.into_inner()`, which, according to the documentation

> Note that care should be taken to not tamper with the underlying stream of data coming in as it may corrupt the stream of frames otherwise being worked with.

So some of the bytes that were read into the buffer were lost when `self.framed.into_inner()` is executed. [`into_parts`](https://docs.rs/tokio-util/0.7.3/tokio_util/codec/struct.Framed.html#method.into_parts), which doesn't lose the underlying buffer, seems like what I actually want.

**Comment by weigangd** [comment]
Hi @minghuaw, thank you very much for your fast response and fixing of the issue. With the new version the version negotiations works as intended.
