### ISSUE TITLE
Io(Custom { kind: UnexpectedEof, error: "early eof" }) on Connection::open

### ISSUE THREAD

**Issue by roblperry** [minghuaw/fe2o3-amqp#99]
I'm receiving an error when attempting to obtain amqps connections to ApacheMQ using fe2o3-amqp version 0.6.1.  I get the same results with native-tls and rustls regardless of if I am running against a local server or an AWS MQ instance. I have have no issue connecting to the local server via amqp. I have confirmed that I can communicate with both servers using an Apache Proton client and confirmed that the cert on the AWS MQ server looks good. 

I recreated this problem using https://github.com/minghuaw/fe2o3-amqp/tree/ec9693ec58ed3ef7bc28f2138fe62ee887a21357/examples/native_tls_connection and https://github.com/minghuaw/fe2o3-amqp/tree/ec9693ec58ed3ef7bc28f2138fe62ee887a21357/examples/rustls_connection changing only the dependency in Cargo.toml to reference 0.6.1 and the url passed to Connection::open.  e.g.:

```
    let mut connection =
        Connection::open("example-connection", "amqps://username:password@localhost:5671")
            .await
            .unwrap();
```
or
```
    let mut connection =
        Connection::open("example-connection", "amqps://username:password@bla-bla-bla-1.mq.us-east-1.amazonaws.com:5671")
            .await
            .unwrap();
```
the full output is:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: UnexpectedEof, error: "early eof" })', amqp_native_tls_test/src/main.rs:8:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I can privately provide the real URL and credentials to an AWS MQ server, if it will help.

**Comment by minghuaw** [comment]
Thanks for raising the issue. I will set up a local Apache MQ environment and look into it.

**Comment by roblperry** [comment]
You rule.  Please let me know if there is anything I can do to help and thank you for creating your awesome library. 

Kudos on the name fe2o3-amqp. Very nice.

**Comment by minghuaw** [comment]
I have got some idea why TLS doesn't work on the local machine. The current implementation defaults to establish TLS before SASL, but apache-activemq seems to want SASL first. This is actually a feature I was planning to add, so that the user can choose whether TLS will be established before SASL or SAL before TLS.

I have yet to find the exact reason for AWS tho, because somehow I was not even able to establish a pure TCP connection to a test apache-activemq instance on AWS. 

Adding the feature shouldn't take me too long. I will keep you updated :)

**Comment by minghuaw** [comment]
I think I have figured it out. The problem is not the order of SASL or TLS.

Apache ActiveMQ uses the alternative TLS establishment specified in the spec (http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-security-v1.0-os.html#doc-tls-alternative-establishment), which performs TLS handshake without exchanging the ['A', 'M', 'Q', 'P', '2', '1', '0', '0'] header. This should then follow a different example [alternative_tls_connection](https://github.com/minghuaw/fe2o3-amqp/tree/main/examples/alternative_tls_connection). 

I have also added a new example [activemq](https://github.com/minghuaw/fe2o3-amqp/tree/main/examples/activemq) which is almost identical to the alternative_tls_connection example but added a little more explanation in the readme.

Given that many brokers seem to use the alternative tls establishment approach, I will add an option to allow an implicit alternative establishment then.

I am not sure if this is the same problem for AWS ActiveMQ yet. I will need to do some more investigations on that.

**Comment by minghuaw** [comment]
v0.6.2 (or #100 ) added a new config in the connection builder that allows implicitly performing alternative TLS establishment instead of manually doing it with `TcpStream`. The `activemq` example has also been updated. It simplifies the usage to something like

```rust
    let addr = "amqps://guest:guest@localhost:5671";
    let mut connection = Connection::builder()
        .container_id("connection-1")
        .native_tls_connector(connector) // Ignore this if only the default one is needed
        .alt_tls_establishment(true) // This asks connection to do TLS handshake without AMQP header exchange
        .open(addr)
        .await
        .unwrap();
```

The example works on my local machine, and I will do a few more tests tomorrow on my AWS free trial

**Comment by roblperry** [comment]
Code above works for me both locally and with my AMS MQ instance. I also found the following code from https://github.com/minghuaw/fe2o3-amqp/blob/main/examples/activemq/src/bin/native_tls.rs helpful.

```rust
    // Customize TLS connector to allow invalid cert (DO NOT do this for work)
    let connector = native_tls::TlsConnector::builder()
        .danger_accept_invalid_certs(true) // FIXME: uncomment this if you just need a quick test with a self-signed cert
        .build()
        .unwrap();
    let connector = tokio_native_tls::TlsConnector::from(connector);
```

Happily the `danger_accept_invalid_certs` is not needed with AMS MQ. 

My first attempt at borrowing code from the rustls example failed, but I'll go try again with a bit more care.

**Comment by roblperry** [comment]
Yay: https://github.com/minghuaw/fe2o3-amqp/blob/main/examples/activemq/src/bin/rustls.rs works with my AWS MQ instance.

**Comment by roblperry** [comment]
fe2o3-amqp version 0.6.2 works with ApacheMQ 5.17.1 via both amqp and amqps as demonstrated by https://github.com/minghuaw/fe2o3-amqp/blob/main/examples/activemq/src/bin/native_tls.rs and https://github.com/minghuaw/fe2o3-amqp/blob/main/examples/activemq/src/bin/rustls.rs.

**Comment by minghuaw** [comment]
> Happily the `danger_accept_invalid_certs` is not needed with AMS MQ.

Great. I have updated the example and removed the `danger_accept_invalid_certs`

**Comment by minghuaw** [comment]
> Yay: https://github.com/minghuaw/fe2o3-amqp/blob/main/examples/activemq/src/bin/rustls.rs works with my AWS MQ instance.

In that case, the following code should also work with either "rustls" or "native-tls" feature enabled (enabling both will actually give you an error). This simply uses the default connector for the chosen TLS crate.

```rust
    let addr = "amqps://guest:guest@localhost:5671";
    let mut connection = Connection::builder()
        .container_id("rust-connection-1")
        .alt_tls_establishment(true) // uses alternative TLS establishement
        .open(addr)
        .await
        .unwrap();
```

**Comment by roblperry** [comment]
Confirmed.  

I removed my call to `native_tls_connector` as well as the code that created the connector and it worked first try. I update Cargo.toml to use rustls instead of native-tls and it again worked first try.  

It was all so smooth that I would have had doubts, except that I had left the logging feature on for the rustls dependency, which caused switching to rustls to give me a wall of log output.
